version: '2'
services:
  pyload:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Andorra
    volumes:
      - ./data/config:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 8000:8000 # Webinterface
      - 9666:9666 # Click 'N' Load
    restart: unless-stopped
