version: "3"

services:
  app:
    image: docker.io/library/spliit:latest
    # ports:
    #   - 3000:3000
    expose:
      - "3000"
    container_name: spliit
    env_file:
      - container.env
    depends_on:
      db:
        condition: service_healthy
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    networks:
      - nginx
      - default

  db:
    image: postgres:latest
    # ports:
    #   - 5432:5432
    env_file:
      - container.env
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nginx:
    external: true
