version: "3"

services:
  app:
    build:
      context: ./spliit
    # ports:
    #   - 3000:3000
    expose:
      - "3000"
    container_name: spliit
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PRISMA_URL: "postgresql://postgres:${DB_PASSWORD}@db"
      POSTGRES_URL_NON_POOLING: "postgresql://postgres:${DB_PASSWORD}@db"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    networks:
      - nginx
      - default
    restart: always

  db:
    image: postgres:16
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backup:
    image: prodrigestivill/postgres-backup-local:16
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - db
    restart: always

networks:
  nginx:
    external: true
