services:
  plex:
    container_name: plex
    #image: plexinc/pms-docker
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    ports:
      - "32400:32400/tcp" # main communication port
      - "3005:3005/tcp"
      #- "8324:8324/tcp" # controlling Plex for Roku via Plex Companion
      - "32469:32469/tcp" # access to the Plex DLNA Server
      - "1900:1900/udp" # access to the Plex DLNA Server
      - "32410:32410/udp" # Plex GDM local discovery
      - "32412:32412/udp" # Plex GDM local discovery
      - "32413:32413/udp" # Plex GDM local discovery
      - "32414:32414/udp" # Plex GDM local discovery
    environment:
      - HOSTNAME=PlexServer
      - TZ=Europe/Andorra
      # - PUID=65534
      # - PGID=65534
      - PUID=911
      - PGID=911
      - VERSION=docker
      - ADVERTISE_IP=${ADVERTISE_IP}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_MEDIA_PATH}:/data
      - ${PLEX_TMP_PATH}:/transcode
    runtime: nvidia
    #deploy:
      #resources:
        #reservations:
          #devices:
            #- driver: nvidia
              #count: 1
              #capabilities: [gpu]

#    networks:
#      - nginx
#
#networks:
#  nginx:
#    external: true
