version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    environment:
      - TZ=Europe/Andorra
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
    ports:
      - "5800:5800"
    volumes:
      - "./data/config:/config:rw"
      - "${DOWNLOAD_DIR}:/output:rw"
