version: '3.7'
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    environment:
      - "TZ=${TIMEZONE}"
      - "TUNNEL_DNS_UPSTREAM=https://1.0.0.1/dns-query,https://1.1.1.1/dns-query"
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"
      - "TUNNEL_DNS_PORT=5053"
    command: proxy-dns
    restart: always
    networks:
      dns-net:
        ipv4_address: 172.20.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    expose:
      - "80"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # DHCP port

    environment:
      - TZ=${TIMEZONE}
      - PIHOLE_DNS_=172.20.0.2#5053 # referencing by name results in "Invalid IP detected in PIHOLE_DNS_: cloudflared#5054"
      #- PIHOLE_DNS_=1.1.1.1 # referencing by name results in "Invalid IP detected in PIHOLE_DNS_: cloudflared#5054"
      - WEBPASSWORD=${PIHOLE_PW}
      - REV_SERVER=true
      - REV_SERVER_TARGET=${PIHOLE_ROUTER_IP}
      - REV_SERVER_DOMAIN=${PIHOLE_NETWORK_DOMAIN}
      - REV_SERVER_CIDR=${PIHOLE_REVERSE_DNS}
      - ServerIP=${PIHOLE_HOST_IP}
      #- ServerIPv6=${PIHOLE_HOST_IPV6}
    #dns:
      #- 127.0.0.1 # "Sets your container's resolve settings to localhost so it can resolve DHCP hostnames [...]" - github.com/pi-hole/docker-pi-hole
      #- 1.1.1.1 # Backup server
    volumes: # store your data between container upgrades
      - "./data/etc-pihole/:/etc/pihole/"
      - "./data/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN) https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    depends_on:
      - "cloudflared"
    restart: always
    networks:
      dns-net:
        ipv4_address: 172.20.0.3
      nginx:

networks:
  dns-net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
  nginx:
    external: true
