services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    environment:
      - TZ=Europe/Andorra
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
    volumes:
      - "./data/config:/config:rw"
      - "${DOWNLOAD_DIR}:/output:rw"
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    external: true
