version: "3"
services:
  receptes-pdf:
    build: .
    container_name: receptes-pdf
    environment:
      - DAV_SERVER=${DAV_SERVER}
      - DAV_SERVER_USER=${DAV_SERVER_USER}
      - DAV_SERVER_PASS=${DAV_SERVER_PASS}
      - DAV_SERVER_INDIR=${DAV_SERVER_INDIR}
      - DAV_SERVER_OUTDIR=${DAV_SERVER_OUTDIR}
      - DAV_CA_CERT_NAME=${DAV_CA_CERT_NAME}
    volumes:
      - ./data/config:/config
      - ./ssl:/etc/davfs2/certs
    restart: unless-stopped
    networks:
      - default
      - bot-owncloud
    extra_hosts:
      - "${DAV_HOSTNAME}:${DAV_HOSTNAME_IP}"
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"

networks:
  bot-owncloud:
    external: true
