version: "3"
services:
  receptes-pdf:
    build:
      context: ./src
      args:
        DAV_CA_CERT_NAME: ${DAV_CA_CERT_NAME}
    container_name: receptes-pdf
    environment:
      - DAV_SERVER=${DAV_SERVER}
      - DAV_SERVER_USER=${DAV_SERVER_USER}
      - DAV_SERVER_PASS=${DAV_SERVER_PASS}
      - DAV_SERVER_INDIR=${DAV_SERVER_INDIR}
      - DAV_SERVER_OUTDIR=${DAV_SERVER_OUTDIR}
    volumes:
      - ./data/config:/config
    restart: unless-stopped
    networks:
      - default
      - bot-owncloud
    extra_hosts:
      - "${DAV_HOSTNAME}:${DAV_HOSTNAME_IP}"
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    labels:
      com.centurylinklabs.watchtower.enable: "false"

networks:
  bot-owncloud:
    external: true
