services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    # network_mode: 'host'
    volumes:
      - ./data/config:/config
      - /tmp/jellyfin:/cache
      - type: bind
        source: ${MEDIA_PATH}
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${SERVER_URL}
      - TZ=Europe/Andorra
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    networks:
      - nginx
    runtime: nvidia
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  volume-permissions-fixer:
    image: bash:4.4
    command: chown 1000:1000 -R /cache
    volumes:
      - /tmp/jellyfin:/cache
    networks:
      - default

networks:
  nginx:
    external: true

