services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.7
    container_name: jellyfin
    user: 1000:1000
    # network_mode: 'host'
    volumes:
      - ./data/config:/config
      - ./tmp:/cache
      - type: bind
        source: ${MEDIA_PATH}
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${SERVER_URL}
      - TZ=Europe/Andorra
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    networks:
      - nginx
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  nginx:
    external: true

