version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/Andorra
    volumes:
      - ./config/prowlarr:/config
    networks:
      - default
      - deluge-network
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/Andorra
    volumes:
      - ./config/sonarr:/config
      - ${DOWNLOADS_DIR}:/downloads
    networks:
      - default
      - deluge-network
    ports:
      - 8989:8989
    restart: unless-stopped

  sonarr_anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_anime
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/Andorra
    volumes:
      - ./config/sonarr_anime:/config
      - ${DOWNLOADS_DIR}:/downloads
    networks:
      - default
      - deluge-network
    ports:
      - 8990:8990
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/Andorra
    volumes:
      - ./config/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
    networks:
      - default
      - deluge-network
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  deluge-network:
    external: true

