services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.6
    container_name: jellyfin
    user: 1000:1000
    # network_mode: 'host'
    volumes:
      - ./data/config:/config
      - /tmp/jellyfin:/cache
      - type: bind
        source: ${MEDIA_PATH}
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${SERVER_URL}
      - TZ=Europe/Andorra
      - NVIDIA_VISIBLE_DEVICES=all
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    runtime: nvidia
    networks:
      - nginx

networks:
  nginx:
    external: true

