version: '3'
services:
  switch-httpd:
    image: php:7.2-apache
    ports:
      - "7000:80"
    volumes:
      - "${GAMES_DIR}:/var/www/html/games:ro"
      - "${PWD}/index.php:/var/www/html/index.php:ro"
